/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificacionRouteImport } from './routes/verificacion'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as MisTurnosRouteImport } from './routes/mis-turnos'
import { Route as MedicosRouteImport } from './routes/medicos'
import { Route as MedicoRouteImport } from './routes/medico'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MedicoIndexRouteImport } from './routes/medico/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MedicoTurnosRouteImport } from './routes/medico/turnos'
import { Route as MedicoPerfilRouteImport } from './routes/medico/perfil'
import { Route as MedicoLoginRouteImport } from './routes/medico/login'
import { Route as MedicoDisponibilidadRouteImport } from './routes/medico/disponibilidad'
import { Route as AdminTurnosRouteImport } from './routes/admin/turnos'
import { Route as AdminMedicosRouteImport } from './routes/admin/medicos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEspecialidadesRouteImport } from './routes/admin/especialidades'

const VerificacionRoute = VerificacionRouteImport.update({
  id: '/verificacion',
  path: '/verificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const MisTurnosRoute = MisTurnosRouteImport.update({
  id: '/mis-turnos',
  path: '/mis-turnos',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosRoute = MedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoRoute = MedicoRouteImport.update({
  id: '/medico',
  path: '/medico',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoIndexRoute = MedicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MedicoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MedicoTurnosRoute = MedicoTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoPerfilRoute = MedicoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoLoginRoute = MedicoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MedicoRoute,
} as any)
const MedicoDisponibilidadRoute = MedicoDisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => MedicoRoute,
} as any)
const AdminTurnosRoute = AdminTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicosRoute = AdminMedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspecialidadesRoute = AdminEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/confirmacion': typeof ConfirmacionRoute
  '/especialidades': typeof EspecialidadesRoute
  '/medico': typeof MedicoRouteWithChildren
  '/medicos': typeof MedicosRoute
  '/mis-turnos': typeof MisTurnosRoute
  '/reservar': typeof ReservarRoute
  '/verificacion': typeof VerificacionRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/admin/turnos': typeof AdminTurnosRoute
  '/medico/disponibilidad': typeof MedicoDisponibilidadRoute
  '/medico/login': typeof MedicoLoginRoute
  '/medico/perfil': typeof MedicoPerfilRoute
  '/medico/turnos': typeof MedicoTurnosRoute
  '/admin/': typeof AdminIndexRoute
  '/medico/': typeof MedicoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/especialidades': typeof EspecialidadesRoute
  '/medicos': typeof MedicosRoute
  '/mis-turnos': typeof MisTurnosRoute
  '/reservar': typeof ReservarRoute
  '/verificacion': typeof VerificacionRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/admin/turnos': typeof AdminTurnosRoute
  '/medico/disponibilidad': typeof MedicoDisponibilidadRoute
  '/medico/login': typeof MedicoLoginRoute
  '/medico/perfil': typeof MedicoPerfilRoute
  '/medico/turnos': typeof MedicoTurnosRoute
  '/admin': typeof AdminIndexRoute
  '/medico': typeof MedicoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/confirmacion': typeof ConfirmacionRoute
  '/especialidades': typeof EspecialidadesRoute
  '/medico': typeof MedicoRouteWithChildren
  '/medicos': typeof MedicosRoute
  '/mis-turnos': typeof MisTurnosRoute
  '/reservar': typeof ReservarRoute
  '/verificacion': typeof VerificacionRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/admin/turnos': typeof AdminTurnosRoute
  '/medico/disponibilidad': typeof MedicoDisponibilidadRoute
  '/medico/login': typeof MedicoLoginRoute
  '/medico/perfil': typeof MedicoPerfilRoute
  '/medico/turnos': typeof MedicoTurnosRoute
  '/admin/': typeof AdminIndexRoute
  '/medico/': typeof MedicoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirmacion'
    | '/especialidades'
    | '/medico'
    | '/medicos'
    | '/mis-turnos'
    | '/reservar'
    | '/verificacion'
    | '/admin/especialidades'
    | '/admin/login'
    | '/admin/medicos'
    | '/admin/turnos'
    | '/medico/disponibilidad'
    | '/medico/login'
    | '/medico/perfil'
    | '/medico/turnos'
    | '/admin/'
    | '/medico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmacion'
    | '/especialidades'
    | '/medicos'
    | '/mis-turnos'
    | '/reservar'
    | '/verificacion'
    | '/admin/especialidades'
    | '/admin/login'
    | '/admin/medicos'
    | '/admin/turnos'
    | '/medico/disponibilidad'
    | '/medico/login'
    | '/medico/perfil'
    | '/medico/turnos'
    | '/admin'
    | '/medico'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirmacion'
    | '/especialidades'
    | '/medico'
    | '/medicos'
    | '/mis-turnos'
    | '/reservar'
    | '/verificacion'
    | '/admin/especialidades'
    | '/admin/login'
    | '/admin/medicos'
    | '/admin/turnos'
    | '/medico/disponibilidad'
    | '/medico/login'
    | '/medico/perfil'
    | '/medico/turnos'
    | '/admin/'
    | '/medico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConfirmacionRoute: typeof ConfirmacionRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  MedicoRoute: typeof MedicoRouteWithChildren
  MedicosRoute: typeof MedicosRoute
  MisTurnosRoute: typeof MisTurnosRoute
  ReservarRoute: typeof ReservarRoute
  VerificacionRoute: typeof VerificacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificacion': {
      id: '/verificacion'
      path: '/verificacion'
      fullPath: '/verificacion'
      preLoaderRoute: typeof VerificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-turnos': {
      id: '/mis-turnos'
      path: '/mis-turnos'
      fullPath: '/mis-turnos'
      preLoaderRoute: typeof MisTurnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos': {
      id: '/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof MedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico': {
      id: '/medico'
      path: '/medico'
      fullPath: '/medico'
      preLoaderRoute: typeof MedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico/': {
      id: '/medico/'
      path: '/'
      fullPath: '/medico/'
      preLoaderRoute: typeof MedicoIndexRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/medico/turnos': {
      id: '/medico/turnos'
      path: '/turnos'
      fullPath: '/medico/turnos'
      preLoaderRoute: typeof MedicoTurnosRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/medico/perfil': {
      id: '/medico/perfil'
      path: '/perfil'
      fullPath: '/medico/perfil'
      preLoaderRoute: typeof MedicoPerfilRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/medico/login': {
      id: '/medico/login'
      path: '/login'
      fullPath: '/medico/login'
      preLoaderRoute: typeof MedicoLoginRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/medico/disponibilidad': {
      id: '/medico/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/medico/disponibilidad'
      preLoaderRoute: typeof MedicoDisponibilidadRouteImport
      parentRoute: typeof MedicoRoute
    }
    '/admin/turnos': {
      id: '/admin/turnos'
      path: '/turnos'
      fullPath: '/admin/turnos'
      preLoaderRoute: typeof AdminTurnosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicos': {
      id: '/admin/medicos'
      path: '/medicos'
      fullPath: '/admin/medicos'
      preLoaderRoute: typeof AdminMedicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/especialidades': {
      id: '/admin/especialidades'
      path: '/especialidades'
      fullPath: '/admin/especialidades'
      preLoaderRoute: typeof AdminEspecialidadesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEspecialidadesRoute: typeof AdminEspecialidadesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMedicosRoute: typeof AdminMedicosRoute
  AdminTurnosRoute: typeof AdminTurnosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEspecialidadesRoute: AdminEspecialidadesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMedicosRoute: AdminMedicosRoute,
  AdminTurnosRoute: AdminTurnosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MedicoRouteChildren {
  MedicoDisponibilidadRoute: typeof MedicoDisponibilidadRoute
  MedicoLoginRoute: typeof MedicoLoginRoute
  MedicoPerfilRoute: typeof MedicoPerfilRoute
  MedicoTurnosRoute: typeof MedicoTurnosRoute
  MedicoIndexRoute: typeof MedicoIndexRoute
}

const MedicoRouteChildren: MedicoRouteChildren = {
  MedicoDisponibilidadRoute: MedicoDisponibilidadRoute,
  MedicoLoginRoute: MedicoLoginRoute,
  MedicoPerfilRoute: MedicoPerfilRoute,
  MedicoTurnosRoute: MedicoTurnosRoute,
  MedicoIndexRoute: MedicoIndexRoute,
}

const MedicoRouteWithChildren =
  MedicoRoute._addFileChildren(MedicoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConfirmacionRoute: ConfirmacionRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  MedicoRoute: MedicoRouteWithChildren,
  MedicosRoute: MedicosRoute,
  MisTurnosRoute: MisTurnosRoute,
  ReservarRoute: ReservarRoute,
  VerificacionRoute: VerificacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
